# action.yml
name: 'Setup makemsix for Windows'
description: 'An GitHub Actions used to initialize the makemsix executable in the Actions.'
author: 'BHznJNs'

runs:
  using: "composite"
  steps:
    - name: Download makemsix.exe
      id: download
      uses: robinraju/release-downloader@v1
      with:
        repository: "BHznJNs/makemsix-build"
        tag: "release-1"
        fileName: "makemsix.zip"
    
    - name: Extract zip archive
      shell: pwsh
      run: |
        $zip = "${{ steps.download.outputs.downloaded_files }}"
        $dest = "$env:RUNNER_TEMP\makemsix-tool"

        if (-not (Test-Path $zip)) {
          Write-Error "makemsix.zip not found at $zip"
          exit 1
        }

        New-Item -ItemType Directory -Path $dest -Force
        Expand-Archive -LiteralPath $zip -DestinationPath $dest -Force

    - name: Add to PATH
      shell: pwsh
      run: |
        $toolPath = "$env:RUNNER_TEMP\makemsix-tool"
        if (-not (Test-Path "$toolPath\makemsix.exe")) {
          Write-Error "makemsix.exe not found in $toolPath"
          exit 1
        }
        Add-Content -Path $env:GITHUB_PATH -Value $toolPath
